feat: serde trait for field and group elements
privacy-scaling-explorations/halo2curves pull request #30
Opened 2023-03-06 22:32 UTC by zhenfeizhang

`serde` is quite useful for downstream libraries. would love to have this feature enabled

2023-03-07 12:04 UTC, han0110 approved these changes
LGTM! But I remember the reason to manually implement `SerdeObject` is to avoid dependency `serde`, so I think it'd be nice to have flag to enable/disable this.

2023-03-07 14:48 UTC, CPerezz requested changes
Please, put this behind a `serde` feature. The derives and the imports as well as the serde dependency. 

Users that don't need it should not pay for it in compilation time.

2023-03-07 14:48 UTC, CPerezz commented on Cargo.toml
> +serde = { version = "1.0", default-features = false, features = ["derive"] }
I'd create a serde feature and import this under it.

2023-03-07 15:33 UTC, zhenfeizhang commented
cool. added in 5b97d1182e855fffe6e22a25aec2f6f7fc8befe0

2023-03-07 16:23 UTC, zhenfeizhang commented
Don't know why CI failed... 
```
 cargo test --verbose --release --all --features asm
 ```
 passed on my local machine

2023-03-07 16:33 UTC, CPerezz commented
> Don't know why CI failed...
> 
> ```
>  cargo test --verbose --release --all --features asm
> ```
> 
> passed on my local machine

No worries. It happens sometimes. Not sure what's the exact issue with the gh-runner TBH.
I triggered it again. Let's hope it works now.

2023-03-07 16:34 UTC, CPerezz approved these changes
LGTM! Thanks for adding the feature!!

2023-03-07 17:51 UTC, merged

2023-03-10 09:33 UTC, han0110 commented
Hi @zhenfeizhang is there any specific reason not re-export `ff` and `group` by default? I think it'd a little awkward for downstream libraries since all of those relying on `halo2curves` now need to specify the `reexport` feature (I think most of them need to import the traits in `ff` and `group`).

If no specific concern I'd suggest to make re-export it by default, what do you think?