fix: Alert if publisher doesn't have cargo-release installed
privacy-scaling-explorations/halo2curves pull request #64
Opened 2023-07-10 08:21 UTC by CPerezz

Resolves: #61 (or at least prevents it to happen again)

2023-07-10 12:15 UTC, huitseeker requested changes
For me, `cargo-release --version` fails on a machine with `cargo-release` installed, see details in inline message.

2023-07-12 11:21 UTC, CPerezz commented on Makefile
> +ifeq (, $(shell cargo-release --version))
I should have tried with the thing installed LOL!
Let me try with grep yes! Thanks for the suggestion @huitseeker !

2023-07-12 11:39 UTC, CPerezz commented
@huitseeker thanks a lot for the suggestion. I should have tested the positive case before filing this. 
Now it should work with your correct suggestion (just hoping there aren't many `release` keywords for other widely used cargo sub-commands hehehe.

2023-07-12 18:59 UTC, huitseeker approved these changes
🙏

2023-07-12 23:58 UTC, han0110 approved these changes
LGTM

2023-07-13 00:05 UTC, merged